[package]
name = "lalg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float_eq = "1.0.1"
itertools = "0.11.0"

[dev-dependencies]
proptest = "1.3.1"
proptest-derive = "0.4.0"
